# 项目相关配置
hanzaitu:

  # 名称
  name: hanzaitu

  # 版本
  version: 1.0.0

  # 获取ip地址开关
  addressEnabled: false

  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

  # 聊天记录保留时间 单位 小时
  # chatHistoryRetentionTime: 24

  #profile: prod
server:
  port: 6679

# Spring配置
spring:
  profiles:
    active: prod
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  100MB
      # 设置总上传的文件大小
      max-request-size:  500MB
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: a12345678
    # 连接超时时间
    timeout: 10s
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://rm-bp1pknp3n6ju8e9ruko.mysql.rds.aliyuncs.com:3306/hanzaitu?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
        username: test_wuyi
        password: VZOvXp#tW&HtXaKH
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: false
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 日志配置
logging:
  level:
    com.hanzaitu.**: debug
    com.hanzaitu.**.mapper: debug
    org.springframework: info
    sql: debug
  config: classpath:config/logback-spring.xml


# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.hanzaitu.ai.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml


mj:
  translate-way: GPT
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10

mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.hanzaitu.**.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml

hzt:
  auth:
    enable: true
    session-expire-time: 1500
    exclusionUrl: .*(/webjars/.*|/swagger-resources.*|/v3/api-docs|/error|/csrf|/health|/swagger-ui/*|/swagger-ui.*|swagger-ui/index.html|/config/.*|/profile/.*|/static/.*|/draw/square/list|/draw/square/label)
    access-token-name: Access-Token-Hzt
    access-token-key-prefix: hzt:token:access_token
    session-class: com.hanzaitu.common.core.session.UserSessionDTO
  config:
    enable-thread-pool: true
    enable-mybatis: true
    enable-redis: true
    enable-scheduler: true
    enable-mq: true
    enable-xxl-job: true
  swagger:
    security-url: /user/signin
    base-package: com.hisetek.hzt
  staticDir: "static"
#快递100
kd100:
  sms:
    url:
    key:
    userid:
    seller:
    tid:
      - 8020 #验证码

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

